### ISSUE TITLE
will the code be available?

### ISSUE THREAD

**Issue by IssamLaradji** [Juliachang/SC-CAM#1]
Great paper! will the code be available? thanks!

**Comment by rAm1n** [comment]
+1

**Comment by Mrkkew** [comment]
+1,I think the idea is interesting.

**Comment by Juliachang** [comment]
Hi @IssamLaradji, @rAm1n, @Mrkkew,

Thanks for being interested in our work. The code will be released soon.

**Comment by liuyuan11** [comment]
+1, interesting too!

**Comment by imzyp** [comment]
Will the code be released in the near future?

**Comment by HRanWang** [comment]
when？

**Comment by zbf1991** [comment]
+1

**Comment by HRanWang** [comment]
Hi，Yuting：
感谢分享！请教一下，这个表格给的数据是用CAM生成的伪标签训练分割网络得到的精度，还是用CAM生成的伪标签的精度啊？Class Activation Map
      Model   Train (mIoU)   Val (mIoU)      
       ResNet-38   50.9   49.6   [Weights]  
 
---------- Origin message ----------
>From："juliachang" <notifications@github.com>
>To："Juliachang/SC-CAM" <SC-CAM@noreply.github.com>
>Subject：Re: [Juliachang/SC-CAM] will the code be available? (#1)
>Date：2020-09-23 03:52:30

Closed #1.

--
You are receiving this because you commented.
Reply to this email directly or view it on GitHub:
https://github.com/Juliachang/SC-CAM/issues/1#event-3794938912

**Comment by Juliachang** [comment]
Hi @HRanWang,

The table shows the mIoU of the produced response map rather than the final semantic segmentation. Thanks.

**Comment by HRanWang** [comment]
thanks，response map后生成的伪标签的mIoU有么有呀，评价过伪标签的质量吗，怎么测评呢，用mIoU可以吗？∩▽∩

---------- Origin message ----------
>From："juliachang" <notifications@github.com>
>To："Juliachang/SC-CAM" <SC-CAM@noreply.github.com>
>Subject：Re: [Juliachang/SC-CAM] will the code be available? (#1)
>Date：2020-09-23 13:00:15

Hi @HRanWang,

The table shows the mIoU of the produced response map rather than the final semantic segmentation. Thanks.
