### ISSUE TITLE
Very Strange results with meanIOU

### ISSUE THREAD

**Issue by ChunmengLiu1** [Juliachang/SC-CAM#16]
Thanks for a great job! I'm following your job.
When I run your code,  I got very strange results. As follows,

class  0 background   IU 0.81
class  1 aeroplane    IU 0.00
class  2 bicycle      IU 0.00
class  3 bird         IU 0.00
class  4 boat         IU 0.00
class  5 bottle       IU 0.00
class  6 bus          IU 0.00
class  7 car          IU 0.00
class  8 cat          IU 0.00
class  9 chair        IU 0.00
class 10 cow          IU 0.00
class 11 diningtable  IU 0.00
class 12 dog          IU 0.00
class 13 horse        IU 0.00
class 14 motorbike    IU 0.00
class 15 person       IU 0.00
class 16 pottedplant  IU 0.00
class 17 sheep        IU 0.00
class 18 sofa         IU 0.00
class 19 train        IU 0.00
class 20 tvmonitor    IU 0.00
meanIOU: 0.2713713433526475

I don't change the network, and I just change some positions of the folder. I would like to know if you have ever encountered such a problem and how to solve it, or could you give me some advice on what might be the problem.
 Thanks for your reading and I look forward to hearing from you.

**Comment by U201714643** [comment]
Hi 
I think  Issue  #6 might be useful.

**Comment by ChunmengLiu1** [comment]
Hi,
Thanks for your reply.I have solved the problem.Another solution is to use PIL to read images from the SegmentationClass folder.
In addition, could you please provide detailed description of the following two stages?

best wishes,
liu

---Original---

**Comment by ChunmengLiu1** [comment]
> Hi
> I think Issue #6 might be useful.

Oh, I‘m sorry. I thought you were the author of the paper.
