### ISSUE TITLE
Did you use COCO pre-train weight during training?

### ISSUE THREAD

**Issue by johnnylu305** [Juliachang/SC-CAM#2]
Excuse me. Sorry to bother you, you may be busy with building this project and others. Although the project has not been released, I have a question about it. Did you use the official deeplabv2 resnet-101 model and load COCO pre-train weight during training? Can you share your training method of your deeplabv2 resnet-101 with us? It's fine to reply to me when you are free. If you think this is not an issue, I can close it.

**Comment by johnnylu305** [comment]
I close it since the author has replied to me and their work focus on CAM rather than second-stage.

**Comment by Eli-YiLi** [comment]
so, use coco-pretrained or not?

**Comment by johnnylu305** [comment]
@Eli-YiLi For the second-stage segmentation model training, they use the [public repo](https://github.com/kazuto1011/deeplab-pytorch) which uses the COCO pre-trained weight. But, don't worry, their work focus on CAM.
