### ISSUE TITLE
Which backbone is used

### ISSUE THREAD

**Issue by SharhadBashar** [Juliachang/SC-CAM#20]
In your paper you mention both ResNet-38 and ResNet-101
Which one is used where?

**Comment by wasidennis** [comment]
ResNet-38 is used for training the classification model (generating the initial response map), while ResNet-101 is used for training the final semantic segmentation model. Please check Sec. 3.3 for the details.

**Comment by SharhadBashar** [comment]
So to clarify, your paper is more focused on creating better pseudo ground truths by making better response maps, correct?
The code for the semantic segmentation from these pseudo ground truths that is used to get the results in tables 3 and 4 using ResNet-101 are not included in this github?

**Comment by wasidennis** [comment]
No, it's not included. Please check the Readme file.

**Segmentation network: We utilize the Deeplab-v2 framework [2] with the ResNet-101 architecture [3] as the backbone model to train the segmentation network. Please refer to the repo.**
