### ISSUE TITLE
The final mIoU result is 0 except for the background

### ISSUE THREAD

**Issue by Alice-Shen** [Juliachang/SC-CAM#6]
Does anyone encounter this kind of situation? The final mIoU result is 0 except for the background?

**Comment by OpencvW** [comment]
Hi, I got same error. did you solve this error?

**Comment by Alice-Shen** [comment]
Sorry，I did not solve this problem.

**Comment by OpencvW** [comment]
@Alice-Shen, I solved that problem, I used wrong segmentation files. I should use SegmentationClassAug(you can download it from here: https://www.dropbox.com/s/oeu149j8qtbs1x0/SegmentationClassAug.zip?dl=0) instead of SegmentationClass.

**Comment by Alice-Shen** [comment]
Thank you！ I think I use the wrong segmentation files too.
